

services:
  node-app:
    build: ./project-node
    ports:
      - "3000:3000"
    container_name: final-exam-node
    environment:
      - NODE_ENV=production

  python-app:
    build: ./project-python
    ports:
      - "5000:5000"
    container_name: final-exam-python
    environment:
      - FLASK_ENV=production
